"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Database, GitBranch, KeyRound, Link2, LockKeyhole, Pencil, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";

type Connection={slug:string;name:string;description:string;icon:string;accent:string;sourceType:string;repositoryUrl:string;branch:string;documentPaths:string;lastSyncedAt:string|null};
type FormState={name:string;description:string;icon:string;accent:string;sourceType:string;repositoryUrl:string;branch:string;documentPaths:string;token:string};
const emptyForm:FormState={name:"",description:"",icon:"",accent:"#f4b860",sourceType:"git",repositoryUrl:"",branch:"main",documentPaths:"updates.md",token:""};

export default function AdminClient({userEmail}:{userEmail:string}) {
  const [form,setForm]=useState<FormState>(emptyForm); const [connections,setConnections]=useState<Connection[]>([]); const [editing,setEditing]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  async function loadConnections(){const response=await fetch("/api/admin/projects",{cache:"no-store"});const data=await response.json() as {projects?:Connection[]};if(response.ok)setConnections(data.projects||[]);}
  useEffect(()=>{void loadConnections();},[]);
  function change(name:keyof FormState,value:string){setForm((current)=>({...current,[name]:value}));}
  function startEdit(project:Connection){setEditing(project.slug);setForm({name:project.name,description:project.description,icon:project.icon,accent:project.accent,sourceType:project.sourceType,repositoryUrl:project.repositoryUrl,branch:project.branch,documentPaths:project.documentPaths,token:""});setMessage("");setError("");window.scrollTo({top:0,behavior:"smooth"});}
  function reset(){setEditing(null);setForm(emptyForm);setError("");}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setMessage("");setError("");try{const response=await fetch(editing?`/api/projects/${editing}`:"/api/projects",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const data=await response.json() as {project?:{name:string};error?:string};if(!response.ok)throw new Error(data.error||"Project could not be saved.");setMessage(form.sourceType==="plastic"?`${data.project?.name||"Project"} is connected and waiting for updates.md from the Plastic bridge.`:`${data.project?.name||"Project"} was ${editing?"updated":"connected"} and synced.`);reset();await loadConnections();}catch(cause){setError(cause instanceof Error?cause.message:"Project could not be saved.");}finally{setSaving(false);}}
  async function remove(slug:string){setError("");const response=await fetch(`/api/projects/${slug}`,{method:"DELETE"});const data=await response.json() as {error?:string};if(!response.ok){setError(data.error||"Project could not be removed.");return;}if(editing===slug)reset();setMessage("Project removed from the dashboard. The repository itself was not changed.");await loadConnections();}
  return <main className="admin-shell">
    <header className="admin-topbar"><a href="/"><ArrowLeft/>Back to dashboard</a><img className="admin-brand" src="/todak-studios-logo.png" alt="TODAK STUDIOS"/><span><LockKeyhole/>Owner setup</span></header>
    <section className="admin-layout">
      <div className="admin-intro"><div className="product-kicker"><Database/>Repository connections</div><h1>{editing?"Edit connection":"Connect a project"}</h1><p>{editing?"Change the repository, branch, update file, or access key. Leave the access key empty to keep the existing one.":"Add each repository once. TODAK STUDIOS will securely present its updates.md briefing."}</p><div className="security-note"><KeyRound/><div><strong>Access keys stay on the server</strong><span>Keys and Plastic bridge secrets are encrypted before storage and never shown on the dashboard.</span></div></div><small>Administrator: {userEmail}</small>
        <div className="connection-list"><div className="connection-list-head"><span>Connected projects</span>{editing&&<button onClick={reset}><Plus/>New project</button>}</div>{connections.length?connections.map((project)=><div className="connection-row" key={project.slug}><span className="connection-icon" style={{background:project.accent}}>{project.icon}</span><div><strong>{project.name}</strong><small>{project.repositoryUrl}</small></div><button aria-label={`Edit ${project.name}`} onClick={()=>startEdit(project)}><Pencil/></button><AlertDialog><AlertDialogTrigger asChild><button className="remove-button" aria-label={`Remove ${project.name}`}><Trash2/></button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove {project.name}?</AlertDialogTitle><AlertDialogDescription>This removes the project and its cached updates from TODAK STUDIOS. It does not delete or change the repository.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={()=>void remove(project.slug)}>Remove project</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>):<div className="no-connections">No real repositories connected yet. The dashboard is showing sample projects.</div>}</div>
      </div>
      <form className="admin-form" onSubmit={submit}>
        <div className="form-heading"><span>{editing?`Editing ${form.name}`:"New connection"}</span><p>{editing?"Saved changes trigger a fresh repository sync.":"Fields marked required are needed for the first sync."}</p></div>
        <div className="field-row"><div className="field"><Label htmlFor="name">Project name</Label><Input id="name" required value={form.name} onChange={(event)=>change("name",event.target.value)} placeholder="e.g. Orbit Mobile"/></div><div className="field"><Label htmlFor="icon">Icon letters</Label><Input id="icon" maxLength={3} value={form.icon} onChange={(event)=>change("icon",event.target.value)} placeholder="OM"/></div></div>
        <div className="field"><Label htmlFor="description">Short description</Label><Input id="description" value={form.description} onChange={(event)=>change("description",event.target.value)} placeholder="What this project delivers"/></div>
        <div className="field"><Label htmlFor="sourceType">Connection type</Label><NativeSelect id="sourceType" value={form.sourceType} onChange={(event)=>change("sourceType",event.target.value)}><NativeSelectOption value="git">Git repository</NativeSelectOption><NativeSelectOption value="plastic">Unity Version Control / Plastic</NativeSelectOption><NativeSelectOption value="api">HTTPS API</NativeSelectOption></NativeSelect></div>
        <div className="field"><Label htmlFor="repositoryUrl">{form.sourceType==="git"?"Repository link":form.sourceType==="plastic"?"Plastic repository":"Update API address"}</Label><div className="input-icon">{form.sourceType==="git"?<GitBranch/>:<Link2/>}<Input id="repositoryUrl" required type={form.sourceType==="plastic"?"text":"url"} value={form.repositoryUrl} onChange={(event)=>change("repositoryUrl",event.target.value)} placeholder={form.sourceType==="git"?"https://github.com/team/project":form.sourceType==="plastic"?"TGC/TGC@todakstudios9@unity":"https://api.example.com/project/updates"}/></div><small>{form.sourceType==="git"?"GitHub, GitLab, Bitbucket, or Azure DevOps":form.sourceType==="plastic"?"A local bridge sends updates.md only when its content changes.":"The API can return Markdown or JSON fields named content, updates, markdown, or text."}</small></div>
        <div className="field-row"><div className="field"><Label htmlFor="branch">Branch</Label><Input id="branch" value={form.branch} onChange={(event)=>change("branch",event.target.value)}/></div><div className="field"><Label htmlFor="accent">Project colour</Label><Input id="accent" type="color" value={form.accent} onChange={(event)=>change("accent",event.target.value)}/></div></div>
        <div className="field"><Label htmlFor="documentPaths">Update file</Label><Input id="documentPaths" value={form.documentPaths} onChange={(event)=>change("documentPaths",event.target.value)}/><small>The first file is required and triggers dashboard changes. Use updates.md unless your repository uses another path.</small></div>
        <div className="field"><Label htmlFor="token">{form.sourceType==="plastic"?"Bridge secret":"Read-only access key"} {editing&&<span className="optional">— optional</span>}</Label><div className="input-icon"><KeyRound/><Input id="token" type="password" required={!editing} value={form.token} onChange={(event)=>change("token",event.target.value)} placeholder={editing?"Leave empty to keep the existing key":form.sourceType==="plastic"?"Paste the generated bridge secret":"Paste the repository access key"}/></div></div>
        <Button type="submit" disabled={saving}>{saving?(editing?"Saving and syncing…":"Connecting and reading…"):(editing?"Save changes":"Connect project")}</Button>
        {editing&&<Button type="button" variant="outline" onClick={reset}>Cancel editing</Button>}
        {message&&<div className="success-message"><CheckCircle2/>{message}<a href="/">View dashboard</a></div>}{error&&<div className="error" role="alert">{error}</div>}
      </form>
    </section>
  </main>;
}
